# Generated by Django 4.2.4 on 2023-08-24 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='path',
            new_name='imagem_produto',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='nome_card',
            new_name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='site',
            name='primeiro_texto',
        ),
        migrations.RemoveField(
            model_name='site',
            name='segundo_texto',
        ),
        migrations.AddField(
            model_name='site',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
