# Generated by Django 4.2.4 on 2023-08-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_rename_path_site_imagem_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='imagem_produto',
            field=models.ImageField(upload_to=''),
        ),
    ]
