# Generated by Django 4.2.4 on 2023-09-04 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_carrossel_buttom_carrossel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='date_create',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
